HardstyleFestivals/Controllers/API/FestivalsController.cs
using AutoMapper;
using HardstyleFestivals.Dtos;
using HardstyleFestivals.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Data.Entity;//nodig voor de "include" (eager loading)

namespace HardstyleFestivals.Controllers.API
{

    //Dit is een API controller in plaats van een MVC controller. (in .net core zullen dezet twee verschillende projecten samengevoegd zijn).
    //een API controller retourneert data in plaats van Html views. Dus ".../api/Getfestivals" in de URL geeft geen mooie view met bijvoorbeeld een tabel 
    //met alle festivals, maar een lijst in XML van alle festivals. Deze API is dus geschikt om uit te lezen door andere machines 
    //(Een API is een website voor machines zoals kristof het altijd zegt)
    public class FestivalsController : ApiController
    {

        private ApplicationDbContext _context;

        public FestivalsController ()
	    {
            _context = new ApplicationDbContext();
	    }

        //let op de conventie: /api/festivals gaat naar functie "GetFestivals"

        //zonder dto's:
        ////GET /api/festivals
        //public IEnumerable<Festival> GetFestivals()
        //{
        //    //In een API retourneren we dus geen view met HTML en alles erop en eraan, maar we retourneren alleen een lijstje met data. 
        //    //het genereren van de HTML wordt op de client gedaan (door bijvoorbeeld de "Datatables" library)
        //    return _context.Festivals.ToList();
        //}

        //Met Dto's
        //GET /api/festivals
        public IEnumerable<FestivalDto> GetFestivals()
        {
            return _context.Festivals.
                Include(f => f.ServiceProvider) //(eager loading! Zo wordt het het serviceprovider object meegenomen bij het festival!)
                .ToList()
                .Select(Mapper.Map<Festival, FestivalDto>); //(delegate in de select)
        }


        //Zonder Dto's
        ////GET /api/festivals
        //public Festival GetFestival(int Id)
        //{
        //    var festival = _context.Festivals.SingleOrDefault(f=>f.Id==Id);

        //    if (festival == null)
        //        throw new HttpResponseException(HttpStatusCode.NotFound);

        //    return festival;
        //}

        //Met Dto's
        //GET /api/festivals
        //public FestivalDto GetFestival(int Id)
        //{
        //    var festival = _context.Festivals.SingleOrDefault(f => f.Id == Id);

        //    if (festival == null)
        //        throw new HttpResponseException(HttpStatusCode.NotFound);

        //    //map festival to festivalDto (=copy all properties with the same name)
        //    var festivalDto = Mapper.Map<Festival, FestivalDto>(festival);
        //    return festivalDto;

        //}
        //met IHttpActionResult als returnwaarde ipv een Dto.
        //Dit kan je gebruiken als je aan alle REST regels wilt voldoen.
        //GET /api/festivals
        public IHttpActionResult GetFestival(int Id)
        {
            var festival = _context.Festivals.SingleOrDefault(f => f.Id == Id);

            if (festival == null)
                return NotFound();

            //map festival to festivalDto (=copy all properties with the same name)
            var festivalDto = Mapper.Map<Festival, FestivalDto>(festival);
            return Ok(festivalDto);

        }




        //POST /api/Festvals       
        [HttpPost] //voeg deze data annotation toe om ervoor te zorgen dat de method alleen draait bij een post request.
        public Festival CreateFestival(Festival festival)
        {
            //eerst even checken of he formulier goed is ingevuld
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            _context.Festivals.Add(festival);
            _context.SaveChanges();

            return festival;
        }


        //PUT /api/festivals/1
        //Updaten van een festival, geef het id van het betreffende festival mee en een ingevuld festival object
        [HttpPut]
        public void UpdateFestival(int Id, Festival festival) 
        {
            //eerst even checken of he formulier goed is ingevuld
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var festivalInDb = _context.Festivals.SingleOrDefault(f => f.Id == Id);
            if (festivalInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            //(dit kan sneller met de "automapper" tool)
            festivalInDb.Datum = festival.Datum;
            festivalInDb.Naam = festival.Naam;
            festivalInDb.NaamDesc = festival.NaamDesc;
            festivalInDb.Website = festival.Website;
            festivalInDb.TicketsURL = festival.TicketsURL;
            festivalInDb.PrijsEarly = festival.PrijsEarly;
            festivalInDb.PrijsLate = festival.PrijsLate;
            festivalInDb.KostService = festival.KostService;
            festivalInDb.KostBetaling = festival.KostBetaling;
            festivalInDb.YoutubeCode = festival.YoutubeCode;
            festivalInDb.Beschrijving = festival.Beschrijving;
            festivalInDb.Muziek = festival.Muziek;
            festivalInDb.StartVVK = festival.StartVVK;
            festivalInDb.Uitverkocht = festival.Uitverkocht;

            _context.SaveChanges();

        }


        //DELETE /api/festivals/1
        [HttpDelete]
        public string DeleteFestival(int Id)
        {
            var festivalInDb = _context.Festivals.SingleOrDefault(f => f.Id == Id);
            if (festivalInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.Festivals.Remove(festivalInDb);
            _context.SaveChanges();

            return "succes";

        } 



    }
}

HardstyleFestivals/Views/Festivals/FestivalForm.cshtml
@model HardstyleFestivals.ViewModels.FestivalFormViewModel

@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Festival</h2>

@*//create open and closing form tags*@
@using (Html.BeginForm("Save", "Festivals"))  //bij het submitten van dit form wordt actionresult "Save" aangeroepen op de controller
{

    <div class="form-group">
        @Html.LabelFor(m => m.Festival.Naam, new { @class = "groenetekst" })
        @Html.TextBoxFor(m => m.Festival.Naam, new { @class = "form-control" })
        @Html.ValidationMessageFor(m=>m.Festival.Naam )
    </div>
    <div class="form-group">
        <label class="groenetekst" for="NaamDesc">Naam evenement (volledig)</label>
        @Html.TextBoxFor(m => m.Festival.NaamDesc, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Festival.Datum)
        @Html.TextBoxFor(m => m.Festival.Datum, "{0:d-MM-yyyy}", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Festival.Datum)
    </div>
    <div class="form-group">
        <label for="Website">URL van evenement website</label>
        @Html.TextBoxFor(m => m.Festival.Website, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="TicketsURL">URL van ticketverkoop pagina</label>
        @Html.TextBoxFor(m => m.Festival.TicketsURL, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="PrijsEarly">Early prijs (indien van toepassing)</label>
        @Html.TextBoxFor(m => m.Festival.PrijsEarly, new { @class = "form-control" })       
    </div>
    <div class="form-group">
        <label for="PrijsLate">(Late) Prijs</label>
        @Html.TextBoxFor(m => m.Festival.PrijsLate, new { @class = "form-control" })       
    </div>


    //dit moet een dropdownlist worden
    <div class="form-group">
        @Html.LabelFor(m => m.Festival.ServiceProviderId)
        @Html.DropDownListFor(m => m.Festival.ServiceProviderId, //dit is de waarde die opgeslagen moet worden in de festivaltabel 
                                   new SelectList(Model.ServiceProviders, "Id", "Naam"), //dit is de lijst met values en texts die in de dropdownlist komt
                                   "kies provider",
                                   new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Festival.ServiceProvider)
    </div>


    <div class="form-group">
        <label for="KostService">Service kosten va ticketprovider</label>
        @Html.TextBoxFor(m => m.Festival.KostService, new { @class = "form-control" })       
    </div>
    <div class="form-group">
        <label for="KostBetaling">Kosten van ideal betaling</label>
        @Html.TextBoxFor(m => m.Festival.KostBetaling, new { @class = "form-control" })        
    </div>
    <div class="form-group">
        <label for="YoutubeCode">Youtube code (de code van cijfers en letters aan het einde van de url van een youtube filmpje)</label>
        @Html.TextBoxFor(m => m.Festival.YoutubeCode, new { @class = "form-control" })       
    </div>
    <div class="form-group">
        <label for="Beschrijving">URL van evenement website</label>
        @Html.TextBoxFor(m => m.Festival.Beschrijving, new { @class = "form-control" })       
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Festival.Muziek)
        @Html.TextBoxFor(m => m.Festival.Muziek, new { @class = "form-control" })       
    </div>
    <div class="form-group">
        <label for="StartVVK">Start Voorverkoop datum</label>
        @Html.TextBoxFor(m => m.Festival.StartVVK, new { @class = "form-control" })        
    </div>
    
    
    //hiddenfield voor de id (die hebben we nodig als we updaten ipv nieuw saven)
    @Html.TextBoxFor(m => m.Festival.Id)
    <button type="submit" class="btn btn-primary">Save</button>

   
    //zo voeg je specifieke css toe aan alleen deze pagina (zie _layout.cshtml)
    @section ViewSpecificStyles {
    <link href="@Url.Content("~/Content/FestivalFormStyle.css")" rel="stylesheet" type="text/css" />
    }


    //zo voeg je specifieke scripts toe aan alleen deze pagina (zie _layout.cshtml)
    @section ViewSpecificScripts {
        @Scripts.Render("~/bundles/jqueryval");
           
    }

}

HardstyleFestivals/Views/Festivals/ReadOnlyList.cshtml
@model HardstyleFestivals.ViewModels.FestivalsListViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lijst van Hardstyle Festivals. Opgehaald via viewModel, niet editable</h2>



<table id="Festivals" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Festival</th>
            <th>ServiceProvider</th>           
        </tr>
    </thead>
    <tbody>
        @foreach (var festival in Model.lstFestivals)
        {
            <tr>
                <td>@festival.Naam</td>
                <td>@festival.ServiceProvider.Naam </td>               
            </tr>
        }


    </tbody>



</table>




@section ViewSpecificScripts
{
    <script>
        $(document).ready(function () {

            //Koppel "datatables" functionaliteit aan de festivals tabel.            
            $("#Festivals").DataTable();            
        
        });
    </script>

}